version: '3.1'

services:
  db_senatskiy_ao:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  adminer_senatskiy_ao:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  grafana_senatskiy_ao:
    image: grafana/grafana:5.1.0
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-volume:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123456

